version: 2
jobs:
  build:
    machine: true
    environment:
      USER_NAME: circleci
      USER_UID: 1001
      USER_GID: 1001
      TZ: Europe/Berlin
    steps:
      - checkout
      - run:
          name: Build dockered-slurm image and run tests
          command: |
            cd ./dockered-slurm
            docker build -t slurm-docker-cluster:17.02.11 .
            docker-compose up -d
            sleep 5
            ./register_cluster.sh
            docker exec slurmctld python36 /cluster_tools/setup.py install
            docker exec c1 python36 /cluster_tools/setup.py install
            docker exec c2 python36 /cluster_tools/setup.py install
            docker exec slurmctld python36 /cluster_tools/slurm_example.py
            docker-compose down
