version: 2
jobs:
  build:
    machine: true
    environment:
      USER_NAME: circleci
      USER_UID: 1001
      USER_GID: 1001
      TZ: Europe/Berlin
    steps:
      - checkout
      - run: cd ./dockered-slurm
      - run: docker build -t slurm-docker-cluster:17.02.11 .
      - run: docker-compose up -d
      - run: docker exec slurmctld python36 /cluster_tools/setup.py install
      - run: docker exec c1 python36 /cluster_tools/setup.py install
      - run: docker exec c2 python36 /cluster_tools/setup.py install
      - run: docker exec slurmctld python36 /cluster_tools/slurm_example.py
      - run: docker-compose down