version: 2
jobs:
  build:
    machine: true
    environment:
      USER_NAME: circleci
      USER_UID: 1001
      USER_GID: 1001
      TZ: Europe/Berlin
    steps:
      - checkout
      - run:
          name: Build dockered-slurm image and run tests
          command: |
            cd ./dockered-slurm
            docker build -t slurm-docker-cluster:17.02.11 .
            docker-compose up -d

            for i in {1..5}; do # retry
              ./register_cluster.sh && s=0 && break || s=$?
              sleep 10
            done

            docker exec slurmctld python36 ../setup.py install
            docker exec c1 python36 ../setup.py install
            docker exec c2 python36 ../setup.py install
            docker exec slurmctld python36 ../slurm_example.py
            docker exec slurmctld python36 -m pytest ../test.py
            docker-compose down
